## Nathan Anderson-Hobbs
### PUBPOL 599 B Visual Analytics
### Multivariate Exercises
#### March 20, 2019

```{r warning=FALSE, message=FALSE}
#loading libraries
library(openxlsx)
library(ggplot2)
library(ggiraphExtra)
library(dotwhisker)
library(broom)
library(dplyr)
library(margins)
```

### Improving a descriptive plot
```{r, message=FALSE, warning=FALSE}

link3="https://github.com/EvansDataScience/data/raw/master/safeCitiesIndex.xlsx"

safe3x=read.xlsx(link3)

safe3x$min=apply(safe3x[,c(2:5)],1,min)

safe3x$min=rank(safe3x$min,ties.method ='first' )

cityRk=as.factor(safe3x[order(safe3x$min),]$city)

safe3x$city=factor(safe3x$city,
                   levels= cityRk,
                   labels = cityRk,
                   ordered = T)

safe3x$min=NULL

some=c("Manila","Lima", "Washington DC","Tokyo")

subSafe1=safe3x[safe3x$city %in% some,]

base = ggRadar(subSafe1,aes(group='city'),
               alpha = 0,legend.position="bottom") 

base1 = base + labs(title='Safety Index Scores by City',
                    subtitle='Tokyo scores highest in all categories',
                    caption='Source: NEC Safe Cities Index 2017')

base2 =  base1 + theme(legend.title=element_blank(),
               plot.title=element_text(size=17,
                                       face='bold',
                                       hjust=0.5),
               plot.subtitle=element_text(hjust=0.5),
               plot.margin=unit(c(.25,0,0,0),"cm"),
               axis.ticks=element_blank(),
               axis.text.y=element_blank(),
               axis.text.x=element_text(size=7),
               panel.background=element_rect(fill='white'),
               panel.grid=element_line(color='gray90'))

base2
```

### Improving an inferential plot
```{r, message=FALSE, results='hide'}
safe4=read.xlsx(link3)

model1=lm(PERSONAL~HEALTH+INFRASTRUCTURE,data=safe4[,-1])

model1_t = tidy(model1) %>% 
    mutate(model = "Model 1")

model2=lm(PERSONAL~.,data=safe4[,-1])

model2_t <- tidy(model2) %>% mutate(model = "Model 2")

allModels=rbind(model1_t, model2_t)

cut=median(safe4$PERSONAL)
safe4$PERSONAL_bi=ifelse(safe4$PERSONAL>cut,
                         1,0)

logit_PERSONAL = glm(PERSONAL_bi~ .,
                          data = safe4[,-c(1,5)],
                          family = "binomial")


margins_logit_PERSONAL = margins(logit_PERSONAL) 

marginalSummary=summary(margins_logit_PERSONAL)

as.data.frame(marginalSummary)

digi=cplot(logit_PERSONAL, "DIGITAL",draw = F)
```


```{r}
base = ggplot(digi, aes(x = xvals)) 

p1= base + geom_ribbon(aes(ymin = lower, ymax = upper), 
                       fill = "grey90",
                       show.legend=TRUE)

p2 = p1 + geom_line(aes(y = yvals)) 

p3= p2 + labs(title='Marginal Effects of Digital Security Index on Personal Security Index',
              subtitle="Digital security index values below 50 not associated with high personal security index",
              x= "Digital Security Index", y="Predicted Value of Personal Security Index",
              caption='Source: NEC Safe Cities Index 2017')

p4 = p3 + theme(plot.title=element_text(size=15,
                                   hjust=0.5),
           plot.subtitle=element_text(size=10,
                                      hjust=0.5),
           panel.background=element_rect(fill='white'),
           panel.grid=element_line(color='gray90'),
           axis.line=element_line(color='black'))

p5 = p4 + geom_vline(xintercept = 50, lty = 2)

p5 + annotate("text", x = 78, y = 0.6,
                   label = "Gray area indicates \n95% confidence interval", size = 3.5)

```

